apiVersion: v1
kind: Service
metadata:
   name: authentication-server
   namespace: data 
   labels:
      id: authentication-server
spec:
  type: ClusterIP
  selector:
     pod: authentication
  ports:
  - targetPort: 8080
    port: 80