apiVersion: v1
kind: Service
metadata:
   name: cart-manager
   namespace: data 
   labels:
      id: cart-manager
spec:
  type: ClusterIP
  selector:
     pod: cart
  ports:
  - targetPort: 8080
    port: 80