apiVersion: v1
kind: Service
metadata:
   name: catalog-data-sender
   namespace: data 
   labels:
      id: catalog-data-sender
spec:
  type: ClusterIP
  selector:
     pod: catalog 
  ports:
  - targetPort: 8080
    port: 80