apiVersion: v1 
kind: Service 
metadata:
     name: frontend-lb 
     namespace: frontend
     labels:
       id: frontend

spec:
   type: ClusterIP
   selector :
      pod: frontend
   ports:
   - name: http-frontend
     targetPort: 8080
     port: 80 

     