apiVersion: batch/v1
kind: Job
metadata:
   name: job-1
   namespace: job
spec:
  completions: 1
  template: 
     spec:
       restartPolicy: Never
       serviceAccountName: sql-client 
       containers:
       - name: cnt-1
         image: us-central1-docker.pkg.dev/PROJECT_ID/repo-vikretha/cloudsql-data-populator
         envFrom:
            - secretRef:
                name: sql-cred
        
