apiVersion: v1
kind: Service
metadata:
   name: order-manager
   namespace: data 
   labels:
      id: order-manager
spec:
  type: ClusterIP
  selector:
     pod: order-manager
  ports:
  - targetPort: 8080
    port: 80